import { 
  InternProfile, 
  InternProject, 
  InternTask, 
  LeaderboardEntry, 
  Announcement, 
  CertificateItem, 
  NotificationItem 
} from './types';

export const MOCK_INTERN_PROFILE: InternProfile = {
  name: 'Rishab Saini',
  role: 'Full Stack Engineering Intern',
  email: 'rishab.saini@ailearnx.com',
  phone: '+91 98765 43210',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=300&auto=format&fit=crop&q=80',
  college: 'IIT Delhi / Computer Science & Engineering',
  batch: 'Summer 2026 Batch',
  domain: 'Full Stack Web & AI Systems',
  level: 'Level 3 - Senior Intern 🚀',
  performanceScore: 96.5,
  tasksAvailable: 12,
  currentStipend: '₹10,000 / mo',
  expectedStipend: '₹12,500 / mo',
  skills: ['Next.js 16', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'FastAPI', 'Tailwind CSS'],
  github: 'https://github.com/rishab-saini',
  linkedin: 'https://linkedin.com/in/rishabsaini',
  portfolio: 'https://rishabsaini.dev',
  joinDate: '15 June 2026',
};

export const MOCK_CURRENT_PROJECT: InternProject = {
  id: 'p-101',
  title: 'AI-Powered Real-Time Code Reviewer & CI/CD Bot',
  description: 'Building a microservice pipeline using Next.js 16 App Router, FastAPI LLM agents, and PostgreSQL to automatically review GitHub pull requests.',
  category: 'Full Stack & AI',
  thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
  progress: 78,
  stage: 'Stage 4: WebSocket Live Notification Stream',
  mentor: {
    name: 'Girish',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Lead Full Stack Mentor',
  },
  nextDeadline: 'Aug 05, 2026 (6:00 PM)',
  taskStatus: 'In Review with Mentor',
  techStack: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'Docker'],
  repoUrl: 'https://github.com/ai-learnx/ai-code-reviewer-bot',
};

export const MOCK_TASKS: InternTask[] = [
  {
    id: 't-1',
    title: 'Setup WebSocket Server for PR Live Log Stream',
    description: 'Implement Socket.io server with authentication JWT tokens to stream AI review logs.',
    status: 'in_progress',
    priority: 'High',
    dueDate: 'Today, 6:00 PM',
    points: 150,
    assignedMentor: 'Girish',
  },
  {
    id: 't-2',
    title: 'Optimize Database Indexing for PullRequest Metadata',
    description: 'Add composite B-tree indexes on repo_id and commit_hash columns in PostgreSQL.',
    status: 'in_progress',
    priority: 'Medium',
    dueDate: 'Aug 03, 2026',
    points: 100,
    assignedMentor: 'Girish',
  },
  {
    id: 't-3',
    title: 'Implement Dark Mode UI Theme Tokens',
    description: 'Design dark slate surface variables according to Linear/Vercel design system.',
    status: 'approved',
    priority: 'Low',
    dueDate: 'Completed',
    points: 80,
    assignedMentor: 'Girish',
  },
  {
    id: 't-4',
    title: 'Deploy FastAPI Engine to AWS ECS Cluster',
    description: 'Create Task Definition and configure Application Load Balancer target group.',
    status: 'submitted',
    priority: 'High',
    dueDate: 'Aug 04, 2026',
    points: 200,
    assignedMentor: 'Arshad N R',
  },
  {
    id: 't-5',
    title: 'Write Unit Tests for GitHub Webhook Verifier',
    description: 'Ensure HMAC SHA-256 signature verification passes for incoming webhooks.',
    status: 'todo',
    priority: 'High',
    dueDate: 'Aug 06, 2026',
    points: 120,
    assignedMentor: 'Girish',
  },
  {
    id: 't-6',
    title: 'Add Sentry Exception Tracking Middleware',
    description: 'Capture backend exception stack traces during LLM token streaming failure.',
    status: 'todo',
    priority: 'Low',
    dueDate: 'Aug 07, 2026',
    points: 90,
    assignedMentor: 'Girish',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    name: 'Dheeraj Kumar Saini',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    college: 'IIT Delhi',
    points: 2850,
    stipend: '₹10,000',
    badge: 'Elite Top Performer 🏆',
    progress: 100,
  },
  {
    rank: 2,
    name: 'Ishika',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    college: 'BITS Pilani',
    points: 2720,
    stipend: '₹10,000',
    badge: 'Full Stipend Recipient 🥇',
    progress: 95,
  },
  {
    rank: 3,
    name: 'Pughazhenthi M',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=150&auto=format&fit=crop&q=80',
    college: 'Anna University',
    points: 2610,
    stipend: '₹10,000',
    badge: 'Full Stipend Recipient 🥇',
    progress: 90,
  },
  {
    rank: 4,
    name: 'Taraka Ratna',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
    college: 'NIT Trichy',
    points: 2540,
    stipend: '₹10,000',
    badge: 'Full Stipend Recipient 🥇',
    progress: 88,
  },
  {
    rank: 5,
    name: 'Vaibhav Pruthi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    college: 'DTU Delhi',
    points: 2480,
    stipend: '₹10,000',
    badge: 'Full Stipend Recipient 🥇',
    progress: 85,
  },
  {
    rank: 6,
    name: 'Rishab Saini (You)',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    college: 'IIT Delhi',
    points: 2420,
    stipend: '₹10,000',
    badge: 'Senior Intern ⭐',
    progress: 82,
  },
  {
    rank: 7,
    name: 'Sagar Torit Bera',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    college: 'Jadavpur University',
    points: 2350,
    stipend: '₹8,500',
    progress: 78,
  },
  {
    rank: 8,
    name: 'Pallavi Pokala',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    college: 'SRM Institute',
    points: 2290,
    stipend: '₹8,500',
    progress: 75,
  },
  {
    rank: 9,
    name: 'Aryan Hooda',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    college: 'PEC Chandigarh',
    points: 2210,
    stipend: '₹8,000',
    progress: 72,
  },
  {
    rank: 10,
    name: 'Ankit Singh',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    college: 'BHU Varanasi',
    points: 2180,
    stipend: '₹8,000',
    progress: 70,
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'a-1',
    title: '🚀 Milestone Review 3: Capstone Submission Window Open',
    category: 'Submission',
    date: 'August 01, 2026',
    author: 'Lead Mentor Girish',
    urgent: true,
    content: 'All summer batch interns must submit their stage 4 pull requests by Friday 6:00 PM for official mentor evaluation and stipend disbursement approval.',
  },
  {
    id: 'a-2',
    title: '📢 Live Workshop: AWS Microservices & Kubernetes Deployment',
    category: 'Event',
    date: 'July 30, 2026',
    author: 'Arshad N R (Lead Cloud Mentor)',
    content: 'Join us live this Wednesday at 4:00 PM IST for a hands-on session on Dockerizing Next.js apps and deploying them to AWS EKS with HTTPS certificates.',
  },
  {
    id: 'a-3',
    title: '📜 Verified Certificate Verification & LOR Guidelines',
    category: 'Guideline',
    date: 'July 25, 2026',
    author: 'AI LearnX Program Director',
    content: 'Interns completing 100% of assigned capstone milestones with a performance score above 90% are automatically eligible for an official Letter of Recommendation.',
  },
];

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: 'cert-01',
    title: 'Industrial Internship Certificate of Excellence',
    type: 'Internship Certificate',
    issueDate: 'July 28, 2026',
    credentialId: 'AILX-INT-2026-8842',
    previewUrl: 'https://images.unsplash.com/photo-1589330694653-aded6fac7718?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    verificationUrl: 'https://ailearnx.com/verify/AILX-INT-2026-8842',
  },
  {
    id: 'cert-02',
    title: 'Full Stack Web & AI Systems Mastery Certificate',
    type: 'Course Completion',
    issueDate: 'June 30, 2026',
    credentialId: 'AILX-[#2563EB]-2026-1194',
    previewUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    verificationUrl: 'https://ailearnx.com/verify/AILX-[#2563EB]-2026-1194',
  },
  {
    id: 'cert-03',
    title: 'Official Letter of Recommendation (LOR)',
    type: 'Letter of Recommendation (LOR)',
    issueDate: 'Pending Completion',
    credentialId: 'AILX-LOR-2026-PENDING',
    previewUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    verificationUrl: 'https://ailearnx.com/verify/AILX-LOR-2026-PENDING',
  },
  {
    id: 'cert-04',
    title: 'Industrial Experience Letter',
    type: 'Experience Letter',
    issueDate: 'Pending Completion',
    credentialId: 'AILX-EXP-2026-PENDING',
    previewUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    verificationUrl: 'https://ailearnx.com/verify/AILX-EXP-2026-PENDING',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n-1',
    title: 'Code Review Approved 🎉',
    message: 'Lead mentor Girish approved your PR #42 for WebSocket Live Stream Engine.',
    time: '15 mins ago',
    read: false,
    type: 'mentor',
  },
  {
    id: 'n-2',
    title: 'Stipend Disbursed 💰',
    message: 'July monthly stipend of ₹10,000 has been credited to your verified bank account.',
    time: '2 hours ago',
    read: false,
    type: 'stipend',
  },
  {
    id: 'n-3',
    title: 'New Milestone Task Assigned',
    message: 'Task #T-5: Write Unit Tests for GitHub Webhook Verifier assigned to you.',
    time: '1 day ago',
    read: true,
    type: 'task',
  },
  {
    id: 'n-4',
    title: 'Submission Reminder',
    message: 'Capstone Stage 4 submission deadline is approaching in 48 hours.',
    time: '2 days ago',
    read: true,
    type: 'announcement',
  },
];
