import { Story } from './types';

export const SUCCESS_STORIES: Story[] = [
  // Video Stories
  {
    id: 'v1',
    name: 'Harsh Agarwal',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Backend Engineer',
    company: 'Tata Consultancy Services (TCS)',
    domain: 'Full Stack',
    course: 'Full Stack Web Development Masterclass',
    projectCompleted: 'YouTube Real-Time Architecture Clone',
    completionYear: '2025',
    rating: 5,
    category: 'video',
    date: '2025-11-10',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    duration: '4:15',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Harsh built a microservices-based video streaming system and converted his internship into a full-time role at TCS.'
  },
  {
    id: 'v2',
    name: 'Ankit Singh',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Frontend Engineer',
    company: 'Infosys',
    domain: 'Full Stack',
    course: 'React & Next.js Enterprise Development',
    projectCompleted: 'Real-Time Social Platform Like X',
    completionYear: '2025',
    rating: 5,
    category: 'video',
    date: '2025-10-15',
    thumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&auto=format&fit=crop&q=80',
    duration: '3:45',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Ankit shares how mentor code reviews helped him crack technical interviews at Infosys.'
  },
  {
    id: 'v3',
    name: 'Abinaya B',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'Web Developer',
    company: 'Zoho',
    domain: 'Full Stack',
    course: 'Full Stack Web Development',
    projectCompleted: 'MakeMyTrip Booking Platform',
    completionYear: '2025',
    rating: 5,
    category: 'video',
    date: '2025-09-20',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    duration: '5:30',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Abinaya transformed her non-CS background into a Web Developer role at Zoho with hands-on project portfolio.'
  },
  {
    id: 'v4',
    name: 'Sagar Torit Bera',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'VAPT Security Analyst',
    company: 'Fornsec Solutions',
    domain: 'Cybersecurity',
    course: 'Ethical Hacking & Android OS Security',
    projectCompleted: 'Android OS Vulnerability Audit System',
    completionYear: '2025',
    rating: 5,
    category: 'video',
    date: '2025-12-01',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    duration: '6:10',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Sagar mastered mobile VAPT testing and secured a lead security role at Fornsec Solutions.'
  },
  {
    id: 'v5',
    name: 'Pughazhenthi M',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=150&auto=format&fit=crop&q=80',
    role: 'AI Engineer',
    company: 'Nexthub Tech',
    domain: 'AI',
    course: 'Generative AI & LLM Systems',
    projectCompleted: 'Automated AI Code Reviewer Bot',
    completionYear: '2026',
    rating: 5,
    category: 'video',
    date: '2026-01-14',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    duration: '4:50',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Pughazhenthi built custom RAG agents and won elite intern performer stipends.'
  },
  {
    id: 'v6',
    name: 'Taraka Ratna',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
    role: 'Cloud Architect',
    company: 'AWS Partner Network',
    domain: 'Cloud',
    course: 'Cloud Engineering & DevOps',
    projectCompleted: 'Kubernetes Multi-Region Deployment',
    completionYear: '2026',
    rating: 5,
    category: 'video',
    date: '2026-02-05',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    duration: '3:55',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Taraka talks about setting up auto-scaling cloud clusters during his AI LearnX internship.'
  },
  {
    id: 'v7',
    name: 'Dhruvi Patel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Frontend Specialist',
    company: 'Indeed',
    domain: 'Full Stack',
    course: 'Modern UI/UX & React Systems',
    projectCompleted: 'High-Scale Job Aggregator Dashboard',
    completionYear: '2025',
    rating: 5,
    category: 'video',
    date: '2025-08-18',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    duration: '5:05',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Dhruvi shares her journey from student project to landing a job at Indeed.'
  },
  {
    id: 'v8',
    name: 'Supreeth A',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    role: 'Mobile Dev Engineer',
    company: 'Tech Mahindra',
    domain: 'Mobile',
    course: 'React Native & iOS Masterclass',
    projectCompleted: 'Cross-Platform Fintech Mobile Wallet',
    completionYear: '2025',
    rating: 5,
    category: 'video',
    date: '2025-07-22',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop&q=80',
    duration: '4:30',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    summary: 'Supreeth built a full offline-first mobile app using React Native & SQLite.'
  },

  // Audio Stories
  {
    id: 'a1',
    name: 'Ishika',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'Data Scientist',
    company: 'Analytics Quotient',
    domain: 'Data Science',
    course: 'Data Science & Predictive Analytics',
    projectCompleted: 'Customer Churn Prediction Pipeline',
    completionYear: '2026',
    rating: 5,
    category: 'audio',
    date: '2026-03-01',
    duration: '2:45',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    quote: 'The weekly 1:1 mentor code reviews gave me immense confidence during technical data science interviews.'
  },
  {
    id: 'a2',
    name: 'Vaibhav Pruthi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Full Stack Engineer',
    company: 'JS Systech',
    domain: 'Full Stack',
    course: 'Full Stack Web Development',
    projectCompleted: 'Real-Time Collaborative Document Editor',
    completionYear: '2025',
    rating: 5,
    category: 'audio',
    date: '2025-11-28',
    duration: '3:10',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    quote: 'AI LearnX provided real industrial tasks. I did not just solve tutorials—I built production-level software.'
  },
  {
    id: 'a3',
    name: 'Saurabh Kumar',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Cloud Security Analyst',
    company: 'Isha Tech Solutions',
    domain: 'Cloud',
    course: 'Cloud Security & Infrastructure',
    projectCompleted: 'Zero-Trust AWS Perimeter Gateway',
    completionYear: '2025',
    rating: 5,
    category: 'audio',
    date: '2025-10-12',
    duration: '2:15',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    quote: 'My mentor helped me debug cloud IAM policies in real-time. That level of hands-on support is unmatched.'
  },
  {
    id: 'a4',
    name: 'Pallavi Pokala',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'QA Automation Engineer',
    company: 'Code Byter',
    domain: 'Full Stack',
    course: 'Software Testing & Automation',
    projectCompleted: 'Cypress & Playwright E2E Suite',
    completionYear: '2025',
    rating: 5,
    category: 'audio',
    date: '2025-09-05',
    duration: '3:30',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    quote: 'I transitioned from manual testing to automation in under 3 months with guidance from lead mentors.'
  },
  {
    id: 'a5',
    name: 'Aryan Hooda',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Full Stack Developer',
    company: 'Isha Immigration',
    domain: 'Full Stack',
    course: 'Web Development & Node.js',
    projectCompleted: 'Immigration Portal & Document Verification',
    completionYear: '2025',
    rating: 5,
    category: 'audio',
    date: '2025-08-30',
    duration: '2:50',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    quote: 'The full stipend reward program kept me motivated to complete my capstone project ahead of schedule.'
  },

  // Written Stories
  {
    id: 'w1',
    name: 'Dheeraj Kumar Saini',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'Software Development Engineer (SDE)',
    company: 'Cognizant',
    domain: 'Full Stack',
    course: 'Enterprise Java & Spring Boot',
    projectCompleted: 'Banking Payment Gateway Integration',
    completionYear: '2026',
    rating: 5,
    category: 'written',
    date: '2026-02-18',
    review: 'Joining AI LearnX was the best decision of my career. The project-based learning model simulates real software engineering teams. I worked directly under mentor Girish and learned how to design REST APIs and handle production errors cleanly.'
  },
  {
    id: 'w2',
    name: 'Palak Khare',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'UI/UX & Frontend Engineer',
    company: 'Wipro Technologies',
    domain: 'Full Stack',
    course: 'Full Stack Web Development',
    projectCompleted: 'Social Media Platform Like X',
    completionYear: '2025',
    rating: 5,
    category: 'written',
    date: '2025-12-10',
    review: 'I had zero confidence in React when I started. But after building a full-blown X clone with WebSocket real-time notifications, recruiters started reaching out to me on LinkedIn directly. Highly recommended!'
  },
  {
    id: 'w3',
    name: 'Tanmay Ghule',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Cybersecurity Analyst',
    company: 'Deloitte',
    domain: 'Cybersecurity',
    course: 'Ethical Hacking & Network Defense',
    projectCompleted: 'Enterprise Network Vulnerability Scanner',
    completionYear: '2025',
    rating: 5,
    category: 'written',
    date: '2025-11-05',
    review: 'The hands-on lab environment for cybersecurity was top tier. Lead mentor Arshad N R walked us through real VAPT methodology step-by-step. Passed my Deloitte interview in 1 round!'
  },
  {
    id: 'w4',
    name: 'Krish Singh',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'AI / ML Research Intern',
    company: 'Fractal Analytics',
    domain: 'AI',
    course: 'Artificial Intelligence & Machine Learning',
    projectCompleted: 'Computer Vision Defect Detection Model',
    completionYear: '2026',
    rating: 5,
    category: 'written',
    date: '2026-01-20',
    review: 'Building ML pipelines with PyTorch and deploying them via FastAPI gave me practical exposure that university courses never provided. Earned full stipend and landed my dream role.'
  }
];
